[tool.poetry]
name = "code_gen"
version = "0.1.0"
description = ""
authors = ["schilkp <schilk.philipp@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

