name: ci-conv

on:
  push:
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install protoc
        run:  sudo apt-get install protobuf-compiler

      - name: Cargo Test
        working-directory: ${{github.workspace}}/frtrace-conv/
        run: cargo test --all

  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - name: Format Check
        working-directory: ${{github.workspace}}/frtrace-conv/
        run: cargo fmt -- --check

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Install protoc
        run:  sudo apt-get install protobuf-compiler

      - name: Lint
        working-directory: ${{github.workspace}}/frtrace-conv/
        run: cargo clippy --all-features -- -D warnings
